### ISSUE TITLE
Add Support For Mac

### ISSUE THREAD

**Issue by AlexanderKhazatsky** [facebookresearch/fairo#1125]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [X ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description
I would like to be able send commands from my Mac to the NUC running the robot. However, Polymetis is not currently available on Mac. Could you please add support for this somehow? It would even be helpful if you could just make a repo for server communication.

## Current Behavior
When I try to install Polymetis on my Mac, it can't find the package. I would like to be able to send commands from my Mac to a NUC.

## Steps to reproduce

Run the installation commands on a Mac.

## Links to any relevant pastes or documents 

N/A
## Checklist

Use this checklist if you are using this issue as a tracker:

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3 ...

**Comment by exhaustin** [comment]
Sorry, Polymetis does not currently support OSX due to having linux-exclusive dependencies. 
A short-term solution would be to run Polymetis within a Docker environment with an ubuntu image on your Mac.

In the long run we may be potentially separating Polymetis into multiple packages, which will enable us to create an OSX release for the user-facing client, but this will not happen anytime soon.
