### ISSUE TITLE
Server Question, Not An Issue

### ISSUE THREAD

**Issue by AlexanderKhazatsky** [facebookresearch/fairo#1374]
Hello! I'm doing some work on communicating between the NUC and the workstation, and I've mainly been doing this over a flask server.

It's possible I'm doing something wrong, but the delay is quite bad (~0.15 sec delay, but I'd like to run at 20 hz).

Although I'm willing to use Polymetis as the server since it supports this anyway (and I assume at a much faster rate), I'd prefer not to so that our codebase stays robot agnostic.

I am curious if you guys have any advice on this? For example, is there an alternative to flask that works much better? I had some trouble figuring out what Polymetis uses under the hood :)

Thanks as always!

**Comment by exhaustin** [comment]
Polymetis uses [gRPC](https://grpc.io/), the interface of which can be found [here](https://github.com/facebookresearch/fairo/blob/main/polymetis/polymetis/protos/polymetis.proto). 

I don't have any experience with flask, but I would try to identify where the bottleneck is along the pipeline (and ensuring that it is due to flask) before making an effort to switch frameworks.

**Comment by AlexanderKhazatsky** [comment]
So I found that it was actually consecutive calls that was making things slow, and sending less calls in bigger packets greatly sped things up.

I'm finding that I can send small vectors of info (~ Length 7) within 20 milliseconds. Is this on the same scale as the Polymetis servers across an ethernet cable? I'd test it myself but my other machine is a Mac so I can't download Polymetis :)

**Comment by 1heart** [comment]
In order to achieve real-time control at 1kHz, the entire control loop must complete within 1ms (deserialize robot state, run Torch policy to get control output, serialize torque, send message over network). So I'm guessing the message serialization/deserialization/communication we're using (i.e. gRPC, or really Protobuf) is orders of magnitude faster on average.

You're likely bottlenecked by (in order): Flask overhead, Python, serialization/deserialization protocol. For a closer-to-the-bare-metal communication, you might try just directly sending bits over [sockets](https://docs.python.org/3/howto/sockets.html), which probably will work just fine for small projects in Python, or try something like [zmq](https://zeromq.org/), gRPC, etc.
