### ISSUE TITLE
Operational Space Controller

### ISSUE THREAD

**Issue by AlexanderKhazatsky** [facebookresearch/fairo#1392]
I’ve posed some issues recently about locking joints when interacting with physical objects. I’ve asked around and some people have suggested an operational space controller. Furthermore, it seems that there are some labs which have built one on top of polymetis already, so there is definitely interest.

Is there any potential for you guys to publish one of these controllers for polymetis?

**Comment by AlexanderKhazatsky** [comment]
Was wondering if you guys had an update on this, no worries if you won't have a cycle for it :)

**Comment by exhaustin** [comment]
Sorry we're short on cycles at the moment, but we can still leave this issue open as a tracker. 
However, I am curious as to the exact definition of an operational space controller, as I thought `set_ee_pose` would fit the bill since it is allowing the user to control the robot in the operational (Cartesian) space rather than the raw joint space.
